apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config # nome do ConfigMap, que guarda o arquivo de configuração do Prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s # define que o Prometheus vai coletar as métricas a cada 5 segundos
    scrape_configs:
      - job_name: 'node-app' # nome da tarefa que coleta as métricas do app Node.js
        static_configs:
          - targets: ['node-service:3123'] # endereço do serviço Node dentro do cluster (usa o endpoint /metrics)
